# Generated by Django 3.2.23 on 2023-12-03 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=24)),
                ('last_name', models.CharField(max_length=24)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDetails',
            fields=[
                ('cd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('c_type', models.CharField(max_length=24)),
                ('forkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
            ],
        ),
    ]
